### ISSUE TITLE
Vertical Labels on BarChart (transform / textAnchor)

### ISSUE THREAD

**Issue by Sineliad** [esbullington/react-d3#329]
Hi there - thanks for the great library!

I was trying to get Vertical Labels for the barchart passing down transform and textAnchor properties with no luck, it gets the default behavior.

Tried several methods but no luck either . Any pointers how it has to be done?

Thanks ;)

**Comment by nickells** [comment]
Hi,

I was able to achieve the following with pure CSS
![image](https://cloud.githubusercontent.com/assets/10698677/16343590/fde46a0e-3a05-11e6-988e-e14c6952ecc1.png)

``` css
.rd3-barchart-xaxis text{
  transform: rotate(65deg) translateX(60px)
}

.rd3-chart {
  height: 350px;
}

```
